<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"><html xmlns="http://www.w3.org/1999/xhtml" lang="en"><head><meta http-equiv="Content-Type" content="text/html;charset=UTF-8"/><link rel="stylesheet" href="../.resources/report.css" type="text/css"/><link rel="shortcut icon" href="../.resources/report.gif" type="image/gif"/><title>ErrorCollector.java</title><link rel="stylesheet" href="../.resources/prettify.css" type="text/css"/><script type="text/javascript" src="../.resources/prettify.js"></script></head><body onload="window['PR_TAB_WIDTH']=4;prettyPrint()"><div class="breadcrumb" id="breadcrumb"><span class="info"><a href="../.sessions.html" class="el_session">Sessions</a></span><a href="../index.html" class="el_report">Junit-r4.11</a> &gt; <a href="index.source.html" class="el_package">org.junit.rules</a> &gt; <span class="el_source">ErrorCollector.java</span></div><h1>ErrorCollector.java</h1><pre class="source lang-java linenums">package org.junit.rules;

import static org.junit.Assert.assertThat;

import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.Callable;

import org.hamcrest.Matcher;
import org.junit.runners.model.MultipleFailureException;

/**
 * The ErrorCollector rule allows execution of a test to continue after the
 * first problem is found (for example, to collect _all_ the incorrect rows in a
 * table, and report them all at once):
 *
 * &lt;pre&gt;
 * public static class UsesErrorCollectorTwice {
 * 	&amp;#064;Rule
 * 	public ErrorCollector collector= new ErrorCollector();
 *
 * &amp;#064;Test
 * public void example() {
 *      collector.addError(new Throwable(&amp;quot;first thing went wrong&amp;quot;));
 *      collector.addError(new Throwable(&amp;quot;second thing went wrong&amp;quot;));
 *      collector.checkThat(getResult(), not(containsString(&amp;quot;ERROR!&amp;quot;)));
 *      // all lines will run, and then a combined failure logged at the end.
 *     }
 * }
 * &lt;/pre&gt;
 *
 * @since 4.7
 */
<span class="fc" id="L34">public class ErrorCollector extends Verifier {</span>
<span class="fc" id="L35">    private List&lt;Throwable&gt; errors = new ArrayList&lt;Throwable&gt;();</span>

    @Override
    protected void verify() throws Throwable {
<span class="fc" id="L39">        MultipleFailureException.assertEmpty(errors);</span>
<span class="fc" id="L40">    }</span>

    /**
     * Adds a Throwable to the table.  Execution continues, but the test will fail at the end.
     */
    public void addError(Throwable error) {
<span class="fc" id="L46">        errors.add(error);</span>
<span class="fc" id="L47">    }</span>

    /**
     * Adds a failure to the table if {@code matcher} does not match {@code value}.
     * Execution continues, but the test will fail at the end if the match fails.
     */
    public &lt;T&gt; void checkThat(final T value, final Matcher&lt;T&gt; matcher) {
<span class="fc" id="L54">        checkThat(&quot;&quot;, value, matcher);</span>
<span class="fc" id="L55">    }</span>

    /**
     * Adds a failure with the given {@code reason}
     * to the table if {@code matcher} does not match {@code value}.
     * Execution continues, but the test will fail at the end if the match fails.
     */
    public &lt;T&gt; void checkThat(final String reason, final T value, final Matcher&lt;T&gt; matcher) {
<span class="fc" id="L63">        checkSucceeds(new Callable&lt;Object&gt;() {</span>
            public Object call() throws Exception {
<span class="nc" id="L65">                assertThat(reason, value, matcher);</span>
<span class="nc" id="L66">                return value;</span>
            }
        });
<span class="fc" id="L69">    }</span>

    /**
     * Adds to the table the exception, if any, thrown from {@code callable}.
     * Execution continues, but the test will fail at the end if
     * {@code callable} threw an exception.
     */
    public Object checkSucceeds(Callable&lt;Object&gt; callable) {
        try {
<span class="fc" id="L78">            return callable.call();</span>
<span class="fc" id="L79">        } catch (Throwable e) {</span>
<span class="fc" id="L80">            addError(e);</span>
<span class="fc" id="L81">            return null;</span>
        }
    }
}
</pre><div class="footer"><span class="right">Created with <a href="http://www.eclemma.org/jacoco">JaCoCo</a> 0.7.0.201403182114</span></div></body></html>